import Head from 'next/head';
import { Logo, Avatar, Card, Button, Icon } from '@tourlane/fusion-you';
import { ComponentPropsWithoutRef, useState } from 'react';
import { css, cx, cva, RecipeVariantProps } from 'fusion-engine/css';
import {
  f,
  Code,
  Container,
  VStack,
  Flex,
  TopAppBar,
  Grid,
  GridItem,
  HStack,
  Box,
  Divider,
  Circle,
  Image,
} from 'fusion-engine/jsx';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container maxW={'full'}>
        <Flex w='full' display={'flex'} justifyContent={'space-between'} py={8}>
          <Logo width={'108px'} />
          <Avatar.Root>
            <Avatar.Image
              src='https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?&w=128&h=128&dpr=2&q=80'
              alt='Colm Tuite'
            />
            <Avatar.Fallback delayMs={600}>CT</Avatar.Fallback>
          </Avatar.Root>
        </Flex>
        <Grid columns={{ base: 1, md: 2, lg: 3 }} gap={6}>
          <GridItem>
            <VStack gap={8}>
              <Card.Root>
                <Card.Header flexDir={'column'} gap={2}>
                  <f.h1 textStyle={'display.sm'}>Titel of the trip</f.h1>
                  <f.p textStyle='label.md'>Germany</f.p>
                </Card.Header>
                <Divider />
                <Card.Body>
                  <VStack gap={4}>
                    <HStack gap={2}>
                      <Box w='full'>
                        <f.h2 textStyle='title.sm' color='on.surface.variant'>
                          Duration
                        </f.h2>
                        <f.p textStyle='body.lg' color='on.surface'>
                          [#] days
                        </f.p>
                      </Box>
                      <Box w='full'>
                        <f.h2 textStyle='title.sm' color='on.surface.variant'>
                          Stops
                        </f.h2>
                        <f.p textStyle='body.lg' color='on.surface'>
                          [#]
                        </f.p>
                      </Box>
                    </HStack>
                    <Box>
                      <f.h2 textStyle='title.sm' color='on.surface.variant'>
                        Interests
                      </f.h2>
                      <f.p textStyle='body.lg' color='on.surface'>
                        [Theme], [Theme], [Theme]
                      </f.p>
                    </Box>
                    <Box>
                      <f.h2 textStyle='title.sm' color='on.surface.variant'>
                        Includes
                      </f.h2>
                      <f.p textStyle='body.lg' color='on.surface'>
                        Accommodation, Transport, Meals
                      </f.p>
                    </Box>
                  </VStack>
                </Card.Body>
                <Divider />
                <Card.Footer
                  justifyContent={'flex-start'}
                  alignItems={'center'}
                >
                  <Box mr='auto'>
                    <f.h2 textStyle='title.sm' color='on.surface.variant'>
                      From
                    </f.h2>
                    <f.p textStyle='body.lg' color='on.surface'>
                      € 1,065 per person
                    </f.p>
                  </Box>
                  <Button variant='tonal'>
                    <Icon icon='material-symbols:edit-outline-sharp' />
                    Edit
                  </Button>
                  <Button>Book</Button>
                </Card.Footer>
              </Card.Root>
              <VStack gap={4}>
                {['A', 'B', 'C', 'D', 'E', 'F'].map((item) => (
                  <Flex
                    key={item}
                    rounded='lg'
                    borderColor='outline.variant'
                    borderWidth={1}
                    cursor={'pointer'}
                    transition={'all'}
                    _hover={{
                      bgColor: 'surface.container.highest',
                    }}
                  >
                    <HStack gap={4} p={4} w='full'>
                      <Circle
                        borderColor='outline.variant'
                        borderWidth={1}
                        size={'10'}
                      >
                        {item}
                      </Circle>
                      <VStack>
                        <f.h2 textStyle='title.sm' color='on.surface.variant'>
                          From
                        </f.h2>
                        <f.p textStyle='body.lg' color='on.surface'>
                          € 1,065 per person
                        </f.p>
                      </VStack>
                    </HStack>

                    <Image
                      src='https://picsum.photos/seed/tech/600/600'
                      alt='123'
                      w='5rem'
                      h='5rem'
                      htmlWidth={'5rem'}
                      htmlHeight='5rem'
                      aspectRatio={1}
                      rounded='inherit'
                    />
                  </Flex>
                ))}
              </VStack>
            </VStack>
          </GridItem>
          <GridItem bgColor='secondary'>second</GridItem>
          <GridItem bgColor='tertiary'>third</GridItem>
        </Grid>
      </Container>
    </>
  );
}
